(function(){
'use strict';
const $=s=>document.querySelector(s),C=window.AdminCore;
let data=null,baseline='',repo=null,active='profile',dirty=false,busy=false,uploads=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const descriptions=[['overview','Overview'],['contribution','Sumbangan saya'],['challenge','Cabaran'],['solution','Penyelesaian'],['process','Proses pembangunan'],['learned','Apa yang dipelajari'],['result','Hasil akhir']];
function status(s,error=false){$('#status').textContent=s;$('#status').classList.toggle('error',error);}
function setBusy(v){busy=v;document.querySelectorAll('button,input,textarea').forEach(b=>b.disabled=v);if(!v&&repo===null&&data)$('#review').disabled=true;}
function mark(){dirty=JSON.stringify(data)!==baseline;$('#dirty-status').textContent=dirty?'Ada perubahan belum diterbitkan.':'Tiada perubahan.';renderPreview();}
function cleanup(){for(const u of uploads.values())URL.revokeObjectURL(u.preview);uploads.clear();}
function imageURL(value){const upload=uploads.get(value);if(upload)return upload.preview;return C.validURL(value)?value:'';}
function img(value){const url=imageURL(value);return url?'<img class="image-preview" src="'+esc(url)+'" alt="Pratonton gambar" loading="lazy">':'';}
function input(label,key,value,type='text'){return '<label>'+label+'<input data-key="'+key+'" type="'+type+'" value="'+esc(value)+'"></label>';}
function media(label,key,value){return '<div class="media-field"><h3>'+label+'</h3>'+img(value)+input('URL gambar atau laluan /assets/...',key,value)+'<label>Upload gambar<input type="file" data-upload="'+key+'" accept="image/png,image/jpeg,image/webp"></label><button type="button" class="small" data-clear="'+key+'">Kosongkan gambar</button><p class="note">JPG, PNG atau WebP. Gambar dikecilkan ke maksimum 1600 px; PNG mengekalkan ketelusan.</p></div>';}
function project(){return data.projects.find(p=>p.slug===active);}
function tabs(){const items=[['profile','01 / Portrait & contact'],...data.projects.map((p,i)=>[p.slug,'0'+(i+2)+' / '+p.name])];$('#tabs').innerHTML=items.map(([id,label])=>'<button type="button" data-tab="'+esc(id)+'" aria-current="'+(active===id)+'">'+esc(label)+'</button>').join('');}
function render(){tabs();if(active==='profile'){$('#fields').innerHTML='<h2>Portrait & contact</h2>'+media('Portrait','portrait',data.portrait)+'<div class="fields">'+[['email','Email'],['linkedin','LinkedIn URL'],['github','GitHub URL'],['itch','Itch.io URL']].map(([key,label])=>input(label,key,data.contacts[key],key==='email'?'email':'text')).join('')+'</div><p class="note">Contact kosong kekal sebagai placeholder dalam portfolio.</p>';}
else{const p=project();$('#fields').innerHTML='<h2>'+esc(p.name)+'</h2><div class="fields">'+[['name','Nama projek'],['type','Jenis projek'],['role','Peranan saya'],['tools','Engine / tools']].map(([k,l])=>input(l,k,p[k])).join('')+input('Warna aksen','color',p.color,'color')+'</div>'+media('Cover projek','image',p.image)+descriptions.map(([k,l])=>'<label>'+l+'<textarea data-key="'+k+'" rows="4">'+esc(p[k])+'</textarea></label>').join('')+input('Gameplay video URL (YouTube, HTTPS atau /assets/video.mp4)','video',p.video)+'<p class="note">Video menggunakan pautan. Upload fail video besar tidak disediakan dalam versi ini.</p><h3>Screenshots</h3>'+p.screenshots.map((s,i)=>'<div class="screenshot-row">'+img(s)+input('Screenshot '+(i+1),'screenshot-'+i,s)+'<label>Upload screenshot<input type="file" data-upload="screenshot-'+i+'" accept="image/png,image/jpeg,image/webp"></label><button type="button" class="small" data-remove="'+i+'">Buang daripada projek</button></div>').join('')+'<button type="button" id="add-screenshot">+ Tambah screenshot</button><p class="note">Membuang gambar daripada projek tidak memadam fail lama di GitHub.</p>';}
renderPreview();}
function setValue(key,value){if(active==='profile'){if(key==='portrait')data.portrait=value;else data.contacts[key]=value;}else if(key.startsWith('screenshot-'))project().screenshots[Number(key.split('-')[1])]=value;else project()[key]=value;mark();}
function renderPreview(){if(active==='profile'){$('#preview').innerHTML=img(data.portrait)+'<h2>FAZLIL</h2>'+Object.entries(data.contacts).map(([k,v])=>'<p><strong>'+esc(k)+'</strong><br>'+esc(v||'[ Belum diisi ]')+'</p>').join('');}else{const p=project();$('#preview').innerHTML=img(p.image)+'<h2>'+esc(p.name)+'</h2><p>'+[p.type,p.role,p.tools].filter(Boolean).map(esc).join(' · ')+'</p>'+descriptions.map(([k,l])=>'<h3>'+l+'</h3><p>'+esc(p[k]||'[ Belum diisi ]')+'</p>').join('')+p.screenshots.map(img).join('');}}
function openEditor(d,connection){data=d;baseline=JSON.stringify(d);active='profile';$('#login').hidden=true;$('#editor').hidden=false;$('#connection').textContent=connection;render();mark();$('#review').disabled=!repo;}
$('#connect-form').addEventListener('submit',async e=>{e.preventDefault();setBusy(true);status('Menyambung dan membaca kandungan terkini…');try{const token=$('#token').value.trim();$('#token').value='';const r=new C.Repository($('#owner').value.trim(),$('#repo').value.trim(),$('#branch').value.trim(),token);const d=await r.load();repo=r;openEditor(d,$('#owner').value+'/'+$('#repo').value+' · '+r.branch);status('Tersambung. Kandungan terkini sudah dimuat.');}catch(err){repo?.logout();repo=null;status(err.message,true);}finally{setBusy(false);}});
$('#demo').onclick=async()=>{setBusy(true);try{const r=await fetch('../content.js',{cache:'no-store'});if(!r.ok)throw Error('Letakkan folder admin di sebelah content.js dan buka melalui website atau local server.');openEditor(C.parseContent(await r.text()),'MOD CUBA / TIDAK MENULIS KE GITHUB');status('Mod cuba: edit dan pratonton tersedia. Keluar dan sambung GitHub untuk menerbitkan.');}catch(err){status(err.message,true);}finally{setBusy(false);}};
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b&&!busy){active=b.dataset.tab;render();}};
$('#content-form').addEventListener('submit',e=>e.preventDefault());
$('#fields').addEventListener('input',e=>{if(e.target.dataset.key)setValue(e.target.dataset.key,e.target.value);});
$('#fields').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.clear)setValue(b.dataset.clear,'');else if(b.dataset.remove!==undefined){project().screenshots.splice(Number(b.dataset.remove),1);mark();}else if(b.id==='add-screenshot'){if(project().screenshots.length>=16){status('Maksimum 16 screenshot setiap projek.',true);return;}project().screenshots.push('');mark();}render();});
async function prepareImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Pilih JPG, PNG atau WebP sehingga 10 MB.');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>32000000)throw Error('Gambar terlalu besar. Kecilkan resolusi dahulu.');const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*ratio));c.height=Math.max(1,Math.round(bitmap.height*ratio));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);const mime=file.type==='image/png'?'image/png':'image/webp',blob=await new Promise(resolve=>c.toBlob(resolve,mime,.85));if(!blob||blob.size>5*1024*1024)throw Error('Gambar masih melebihi 5 MB selepas dikecilkan. Pilih gambar lebih kecil.');return blob;}finally{bitmap.close();}}
$('#fields').addEventListener('change',async e=>{const key=e.target.dataset.upload,file=e.target.files?.[0];if(!key||!file)return;setBusy(true);status('Menyediakan gambar…');try{const blob=await prepareImage(file);if([...uploads.values()].reduce((n,u)=>n+u.blob.size,0)+blob.size>20*1024*1024)throw Error('Had 20 MB gambar dalam satu sesi. Terbitkan atau keluar sebelum tambah lagi.');const ext=blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg',path='assets/uploads/'+Date.now()+'-'+crypto.randomUUID()+'.'+ext,url='/'+path;uploads.set(url,{path,blob,preview:URL.createObjectURL(blob)});setValue(key,url);render();status('Gambar tersedia dalam draf. Tekan Semak & terbitkan untuk menyimpan.');}catch(err){status(err.message,true);}finally{setBusy(false);}});
function neededUploads(){const paths=new Set([data.portrait,...data.projects.flatMap(p=>[p.image,...p.screenshots])]);return [...uploads.entries()].filter(([url])=>paths.has(url)).map(([,u])=>u);}
$('#review').onclick=()=>{try{C.validate(data);if(!dirty){status('Tiada perubahan untuk diterbitkan.');return;}const changed=data.projects.filter((p,i)=>JSON.stringify(p)!==JSON.stringify(JSON.parse(baseline).projects[i])).length;$('#review-summary').textContent=changed+' projek dikemas kini. '+neededUploads().length+' gambar baru. Portrait dan contact yang diubah turut disimpan.';$('#review-dialog').showModal();$('#cancel-review').focus();}catch(err){status(err.message,true);}};
$('#cancel-review').onclick=()=>$('#review-dialog').close();
$('#review-dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#publish').onclick=async()=>{if(!repo||busy)return;setBusy(true);status('Memeriksa versi terkini…');try{await repo.publish(data,neededUploads(),s=>status(s));baseline=JSON.stringify(data);mark();$('#review-dialog').close();status('Berjaya disimpan ke GitHub. Tunggu proses GitHub Pages selesai sebelum semak website.');}catch(err){$('#review-dialog').close();status(err.message+' Draf belum dibuang.',true);}finally{setBusy(false);}};
$('#backup').onclick=()=>{const d={format:'fazlil-admin-draft',content:data,note:'Gambar yang belum diterbitkan tidak disertakan; simpan fail gambar asal.'};const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fazlil-content-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Backup teks dimuat turun. Gambar belum diterbitkan perlu disimpan berasingan.');};
$('#logout').onclick=()=>{if(dirty&&!confirm('Ada perubahan belum diterbitkan. Keluar dan buang draf dalam tab ini?'))return;repo?.logout();repo=null;data=null;dirty=false;cleanup();$('#fields').replaceChildren();$('#preview').replaceChildren();$('#editor').hidden=true;$('#login').hidden=false;$('#token').value='';status('Sudah keluar. Token dan draf dibuang daripada memori tab.');$('#token').focus();};
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
window.addEventListener('pagehide',()=>{repo?.logout();});
window.addEventListener('pageshow',e=>{if(e.persisted){repo=null;$('#review').disabled=true;$('#connection').textContent='SESI TAMAT / DOWNLOAD BACKUP SEBELUM KELUAR';status('Sambungan ditamatkan selepas meninggalkan halaman. Download backup jika perlu, kemudian keluar dan sambung semula.',true);}});
})();
