/* No eval: accept data literals only, including the original commented content.js. */
(function(root){
'use strict';
function parseContent(source){
  const start=source.match(/^(?:\s|\/\/[^\n]*(?:\n|$)|\/\*[\s\S]*?\*\/)*window\.PORTFOLIO\s*=\s*/);
  if(!start)throw Error('Format content.js tidak dikenali. Fail asal tidak diubah.');
  let i=start[0].length,depth=0;const fail=()=>{throw Error('Kandungan bukan data ringkas yang disokong. Fail asal tidak diubah.');};
  function ws(){while(i<source.length){if(/\s/.test(source[i]))i++;else if(source.slice(i,i+2)==='//'){const j=source.indexOf('\n',i);i=j<0?source.length:j+1;}else if(source.slice(i,i+2)==='/*'){const j=source.indexOf('*/',i+2);if(j<0)fail();i=j+2;}else break;}}
  function str(){const q=source[i++];let out='';while(i<source.length){let c=source[i++];if(c===q)return out;if(c==='\\'){c=source[i++];const m={n:'\n',r:'\r',t:'\t',b:'\b',f:'\f',v:'\v','0':'\0'};if(c==='u'||c==='x'){const n=c==='u'?4:2,h=source.slice(i,i+n);if(!new RegExp('^[a-fA-F0-9]{'+n+'}$').test(h))fail();out+=String.fromCharCode(parseInt(h,16));i+=n;}else if(c in m)out+=m[c];else if(['\\',"'",'"','/'].includes(c))out+=c;else fail();}else{if(c==='\n'||c==='\r')fail();out+=c;}}fail();}
  function value(){ws();if(++depth>30)fail();let v,c=source[i];if(c==='"'||c==="'")v=str();else if(c==='{'||c==='['){const array=c==='[',end=array?']':'}';v=array?[]:Object.create(null);i++;ws();while(source[i]!==end){let key;if(!array){ws();if(source[i]==='"'||source[i]==="'")key=str();else{const m=source.slice(i).match(/^[A-Za-z_$][\w$]*/);if(!m)fail();key=m[0];i+=key.length;}if(['__proto__','constructor','prototype'].includes(key)||Object.hasOwn(v,key))fail();ws();if(source[i++]!==':')fail();}const item=value();if(array)v.push(item);else v[key]=item;ws();if(source[i]===end)break;if(source[i++]!==',')fail();ws();}i++;}else{const m=source.slice(i).match(/^(true|false|null|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)/);if(!m)fail();v=JSON.parse(m[0]);i+=m[0].length;}depth--;return v;}
  const data=value();ws();if(source[i]===';')i++;ws();if(i!==source.length)fail();validate(data);return data;
}
const textKeys=['name','type','role','tools','overview','contribution','challenge','solution','process','learned','result','image','video'];
function validURL(s){return !s||/^https:\/\/[^\s]+$/i.test(s)||/^\/assets\/[A-Za-z0-9_./%-]+$/.test(s);}
function validate(d){if(!d||typeof d!=='object'||!d.contacts||!Array.isArray(d.projects)||d.projects.length!==4)throw Error('Empat projek dan contact asal diperlukan.');if(typeof d.portrait!=='string'||!validURL(d.portrait))throw Error('Portrait mesti URL HTTPS atau /assets/...');for(const [k,v] of Object.entries(d.contacts)){if(typeof v!=='string')throw Error('Contact tidak sah.');if(k==='email'){if(v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw Error('Alamat email tidak sah.');}else if(!validURL(v))throw Error('Link contact mesti HTTPS.');}const expected=['ngilai','life-gacha','doodle-survival','hero-must-die'];for(const p of d.projects){if(!expected.includes(p.slug))throw Error('Slug projek tidak dikenali.');for(const k of textKeys)if(typeof p[k]!=='string')throw Error('Medan projek tidak lengkap: '+k);if(!p.name.trim())throw Error('Nama projek diperlukan.');if(!/^#[0-9a-f]{6}$/i.test(p.color))throw Error('Warna projek tidak sah.');if(!Array.isArray(p.screenshots)||p.screenshots.some(v=>typeof v!=='string'||!v||!validURL(v)))throw Error('Link screenshot tidak sah.');if(!validURL(p.image)||!validURL(p.video))throw Error('Link gambar/video mesti HTTPS atau /assets/...');}if(new Set(d.projects.map(p=>p.slug)).size!==4)throw Error('Projek berulang.');return d;}
function serialize(d){validate(d);return '// Updated using FAZLIL Content Studio.\nwindow.PORTFOLIO = '+JSON.stringify(d,null,2)+';\n';}
function decode64(s){return new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));}
function base64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
class Repository{
  constructor(owner,repo,branch,token,fetcher=fetch){if(!/^[\w-]+$/.test(owner)||! /^[\w.-]+$/.test(repo)||!branch.trim())throw Error('Repository tidak sah.');this.base='https://api.github.com/repos/'+encodeURIComponent(owner)+'/'+encodeURIComponent(repo);this.branch=branch;this.token=token;this.fetcher=fetcher;this.head=null;this.tree=null;}
  async api(path,method='GET',body){const r=await this.fetcher(this.base+path,{method,headers:{Authorization:'Bearer '+this.token,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:body?JSON.stringify(body):undefined,cache:'no-store',redirect:'error'});if(!r.ok){const msg=r.status===401?'Token tidak sah atau sudah luput.':r.status===403?'Akses ditolak. Semak Contents: Read and write dan had API.':r.status===404?'Repository, branch atau content.js tidak dijumpai. Semak pilihan repository dalam token.':r.status===422?'GitHub menolak perubahan. Branch mungkin berubah atau dilindungi. Muat semula sebelum cuba lagi.':'Permintaan GitHub gagal ('+r.status+').';throw Error(msg);}return r.json();}
  async load(){const ref=await this.api('/git/ref/heads/'+encodeURIComponent(this.branch));const head=ref.object.sha;const commit=await this.api('/git/commits/'+head);const file=await this.api('/contents/content.js?ref='+head);if(file.encoding!=='base64')throw Error('content.js terlalu besar atau format tidak disokong.');const d=parseContent(decode64(file.content));this.head=head;this.tree=commit.tree.sha;return d;}
  async publish(data,uploads,onProgress=()=>{}){
    const content=serialize(data),ref=await this.api('/git/ref/heads/'+encodeURIComponent(this.branch));if(ref.object.sha!==this.head)throw Error('Repository berubah sejak dibuka. Download backup draf, kemudian keluar dan sambung semula untuk memuat kandungan terbaru.');
    const entries=[];for(let i=0;i<uploads.length;i++){const u=uploads[i];if(!/^assets\/uploads\/[a-zA-Z0-9_.-]+$/.test(u.path))throw Error('Laluan upload tidak sah.');onProgress('Menghantar gambar '+(i+1)+'/'+uploads.length+'…');const blob=await this.api('/git/blobs','POST',{content:base64(new Uint8Array(await u.blob.arrayBuffer())),encoding:'base64'});entries.push({path:u.path,mode:'100644',type:'blob',sha:blob.sha});}
    entries.push({path:'content.js',mode:'100644',type:'blob',content});onProgress('Menyimpan kandungan…');const tree=await this.api('/git/trees','POST',{base_tree:this.tree,tree:entries});const commit=await this.api('/git/commits','POST',{message:'Update portfolio content via admin',tree:tree.sha,parents:[this.head]});
    try{await this.api('/git/refs/heads/'+encodeURIComponent(this.branch),'PATCH',{sha:commit.sha,force:false});}catch(err){try{const check=await this.api('/git/ref/heads/'+encodeURIComponent(this.branch));if(check.object.sha!==commit.sha)throw err;}catch{throw Error('Status simpan belum dapat disahkan. Semak commit di GitHub sebelum cuba lagi. Draf masih ada dalam tab ini.');}}
    this.head=commit.sha;this.tree=tree.sha;return commit.sha;
  }
  logout(){this.token='';}
}
root.AdminCore={parseContent,serialize,validate,validURL,Repository};
})(typeof window==='undefined'?globalThis:window);
